### ISSUE TITLE
SMTP Forwarding from nobody@dlireports?

### ISSUE THREAD

**Issue by gorel** [gorel/dli-reports#106]
This would be cool. Instead of using dlireports@gmail.com, use nobody@dlireports.com

**Comment by XJi** [comment]
Yay, it should be easy to use nobody@direports.com if we know MAIL_PORT number and MAIL_SERVER of dlireports.com I think

**Comment by gorel** [comment]
We investigated this and it would cost $5/month. Yeah, it's not a big price to pay, but since this site is internal, it really doesn't matter.
