### ISSUE TITLE
Use c3 CDN instead of our local copy?

### ISSUE THREAD

**Issue by gorel** [gorel/dli-reports#141]
Less bandwidth usage by us, but do we care?

**Comment by gorel** [comment]
I think we shouldn't actually do this for now. We risk potentially breaking the site in the future.

**Comment by faultyserver** [comment]
I currently have 2-3 cdn-sourced things. It really doesn't matter and also means that important security things automatically get applied (as unimportant as that realistically is).

Adding this wouldn't be a problem, but there's no real reason to.
