### ISSUE TITLE
As a Supervisor, I want to delete old report templates.

### ISSUE THREAD

**Issue by gorel** [gorel/dli-reports#15]
- [x] Create a page for listing all existing report template. 
- [ ] Filter all templates by department, creating time or specific users.
- [ ] Create a checkbox in front of each templates
- [x] Create a “delete” button on the page. Once a supervisor clicks the button, the selected templates will be deleted, and those template information will be removed from database
- [x] The page will be automatically reloaded with all available templates

**Comment by faultyserver** [comment]
The current design doesn't really match this pattern. Instead, supervisors have the ability to delete reports on the "All Reports" index page.

**Comment by ad08fee3** [comment]
This is basically done and will be merged checked as done with the ux0.2 update.
