### ISSUE TITLE
As the Secretary, I want to create new wiki pages for policies.

### ISSUE THREAD

**Issue by gorel** [gorel/dli-reports#16]
- [x] Research best Python web libraries for creating user-content Wikis
- [x] Create the webpage that secretary can create new wiki pages  
- [x] Provide all the empty fields for secretary to fill out the information about the wiki policies.
- [x] After filling out all textfields, secretary can click for submit button to upload new wiki page to the database
- [ ] Support automatic page creation from a *.txt file
- [ ] Research feasibility of importing *.pdf or *.docx files

**Comment by ad08fee3** [comment]
Automatic creation was deferred at DLI's request
