### ISSUE TITLE
As a Manager, I want to delete old report templates.

### ISSUE THREAD

**Issue by gorel** [gorel/dli-reports#7]
- [x] Create a webpage and buttons that managers can click to delete report templates
- [x] Create a database action to remove the template from the database
- [x] Create “hooks” within the Report class API to handle all clean-up automatically (button calls API which does DB actions)
- [x] Create a check that if the report is being favorited by another user, report ownership is transferred

**Comment by ad08fee3** [comment]
This is basically done and will be merged checked as done with the ux0.2 update.

**Comment by gorel** [comment]
Yeah, good call. We can move things into "In Review" as pull requests come in.

This is looking a lot better! Good to see so much stuff is getting completed. I kind of figured so. We had a lot done that just hadn't been connected together yet.
